#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

restore0Dir

runApplication blockMesh
runApplication -s 1 topoSet -dict system/topoSetDict1
runApplication -s 1 refineMesh -dict system/refineMeshDict1 -overwrite
runApplication -s 2 topoSet -dict system/topoSetDict2
runApplication -s 2 refineMesh -dict system/refineMeshDict2 -overwrite

runApplication setAlphaField

runApplication $(getApplication)
