#!/bin/bash
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions    # Tutorial run functions

runApplication blockMesh
#runApplication refineMesh -overwrite
touch test-initAlphaField.foam
restore0Dir
runApplication initAlphaField
#runApplication decomposePar
#runParallel $(getApplication)
#runApplication reconstructPar

#------------------------------------------------------------------------------
